// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package encs.concordia.jsf;

import encs.concordia.jsf.CustomerBean;
import java.io.Serializable;

privileged aspect CustomerBean_Roo_Serializable {
    
    declare parents: CustomerBean implements Serializable;
    
    private static final long CustomerBean.serialVersionUID = 1L;
    
}
