// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package encs.concordia.jsf.converter;

import encs.concordia.jsf.converter.CustomerConverter;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect CustomerConverter_Roo_Configurable {
    
    declare @type: CustomerConverter: @Configurable;
    
}
